### ISSUE TITLE
FileNotFoundError in latest version

### ISSUE THREAD

**Issue by istemihan90** [lewisacidic/graph-extract#2]
`C:\WINDOWS\system32>pip install graph-extract
Collecting graph-extract
  Using cached https://files.pythonhosted.org/packages/30/2a/bbcd58869b72a73e9f8c5c139243ce96e54443bec5996c5da7013c36ecdb/graph-extract-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Users\AR100003\AppData\Local\Temp\pip-install-i5d_ow6o\graph-extract\setup.py", line 15, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'`

This is what I get

**Comment by lewisacidic** [comment]
Hi - this is a really old project that was really a one off for a colleague that I'm afraid probably won't do what you want.  That said, I've fixed the bad build, so you're welcome to try it now!

**Comment by istemihan90** [comment]
Thank you Sir! It worked.
